### ISSUE TITLE
Traceback on first run of pulseeffects

### ISSUE THREAD

**Issue by prometheanfire** [wwmm/pulseeffects#129]
Traceback on first run, this is as of git master from today.

```
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/PulseEffects/application.py", line 67, in do_startup
    self.sie = SinkInputEffects(self.pm)
  File "/usr/lib64/python3.5/site-packages/PulseEffects/sink_input_effects.py", line 20, in __init__
    EffectsBase.__init__(self, self.pm.default_sink_rate, self.settings)
  File "/usr/lib64/python3.5/site-packages/PulseEffects/effects_base.py", line 24, in __init__
    PipelineBase.__init__(self, sampling_rate)
  File "/usr/lib64/python3.5/site-packages/PulseEffects/pipeline_base.py", line 61, in __init__
    self.audio_src.set_property('volume', 1.0)
AttributeError: 'NoneType' object has no attribute 'set_property'
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/PulseEffects/application.py", line 140, in do_command_line
    self.do_activate()
  File "/usr/lib64/python3.5/site-packages/PulseEffects/application.py", line 123, in do_activate
    self.sie.switch_on_all_apps = False
AttributeError: 'Application' object has no attribute 'sie'
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/PulseEffects/application.py", line 147, in do_shutdown
    self.sie.set_state('null')
AttributeError: 'Application' object has no attribute 'sie'
```

**Comment by wwmm** [comment]
Are you sure gstreamer plugins good is installed? This error is happening because the pulsesrc plugin could not be found

**Comment by prometheanfire** [comment]
ah, your right, wrong version is installed, I'll be sure to update the package deps for that

**Comment by prometheanfire** [comment]
even after updating it doesn't look good,

```
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/PulseEffects/application.py", line 67, in do_startup
    self.sie = SinkInputEffects(self.pm)
  File "/usr/lib64/python3.5/site-packages/PulseEffects/sink_input_effects.py", line 20, in __init__
    EffectsBase.__init__(self, self.pm.default_sink_rate, self.settings)
  File "/usr/lib64/python3.5/site-packages/PulseEffects/effects_base.py", line 24, in __init__
    PipelineBase.__init__(self, sampling_rate)
  File "/usr/lib64/python3.5/site-packages/PulseEffects/pipeline_base.py", line 61, in __init__
    self.audio_src.set_property('volume', 1.0)
AttributeError: 'NoneType' object has no attribute 'set_property'
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/PulseEffects/application.py", line 140, in do_command_line
    self.do_activate()
  File "/usr/lib64/python3.5/site-packages/PulseEffects/application.py", line 123, in do_activate
    self.sie.switch_on_all_apps = False
AttributeError: 'Application' object has no attribute 'sie'
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/PulseEffects/application.py", line 147, in do_shutdown
    self.sie.set_state('null')
AttributeError: 'Application' object has no attribute 'sie'
```

These are what I have installed as well.

```
[I] dev-python/gst-python (1.12.3(1.0){xpak}@11/26/2017): A Python Interface to GStreamer
[I] media-libs/gst-plugins-bad (1.12.3(1.0){xpak}@11/26/2017): Less plugins for GStreamer
[I] media-libs/gst-plugins-base (1.12.3(1.0){xpak}@11/20/2017): Basepack of plugins for gstreamer
[I] media-libs/gst-plugins-good (1.12.3(1.0){xpak}@11/26/2017): Basepack of plugins for GStreamer
[I] media-libs/gstreamer (1.12.3(1.0){xpak}@11/20/2017): Open source multimedia framework
[I] media-plugins/gst-plugins-ladspa (1.12.3(1.0){xpak}@11/26/2017 -> 0.10.23-r1(0.10)^t): plugin for gstreamer
```

**Comment by wwmm** [comment]
Run the command `gst-inspect-1.0 | grep -i pulse` and check if you have lines with `pulsesrc` and `pulsesink`. If there is none gstreamer could not find these plugins. Usually this happens when there is a problem with the gstreamer plugins good package

**Comment by prometheanfire** [comment]
I was missing a dependency, media-plugins/gst-plugins-pulse

I'll add it, thanks for bearing with me,  I also added a note to the package to enable the pulseaudio equalizer plugin (default disabled).  Are there any other pulse plugins that need enabling for things like the low/high pass, limiters or the other apps?

**Comment by wwmm** [comment]
Pulseaudio's builtin equalizer is not needed. We do not use it and I would not recommend people to use it together with PulseEffects. The equalizer used in PulseEffects is the parametric equalizer in gst-plugins-good. This gstreamer package also has the panorama, lowpass, highpass and spectrum plugins. From gst-plugins-bad we use the reverberation plugin and the wrapper for ladspa plugins. Make sure you have the gst-plugins-bad package that provides the file `/usr/lib/gstreamer-1.0/libgstladspa.so` as dependency. Otherwise the limiter and the compressor will not work even if `swh-plugins` is installed.

**Comment by prometheanfire** [comment]
The plugins are all good to go, but without adding the following to default.pa for pulseaudio I wasn't able to get the equalizer to show up in the pulseeffects interface.

```
load-module module-dbus-protocol
load-module module-equalizer-sink
```

**Comment by wwmm** [comment]
Something else happened. I do not have any of these modules loaded. And even if they were loaded it does not make any difference as they are not used by PulseEffects.

Run PulseEffects from the command line and post its output here so I can see what is really going on

**Comment by wwmm** [comment]
Snapshots from PE window could also help

**Comment by prometheanfire** [comment]
Here's the output.

```
07:48:17.978 - PulseEffects - INFO - pulseaudio context started
07:48:17.989 - PulseEffects - INFO - connected to server: /run/user/1000/pulse/native
07:48:17.999 - PulseEffects - INFO - server protocol version: 32
07:48:18.10 - PulseEffects - INFO - pulseaudio version: 11.1
07:48:18.11 - PulseEffects - INFO - default pulseaudio source: alsa_input.pci-0000_00_1b.0.analog-stereo
07:48:18.11 - PulseEffects - INFO - default pulseaudio sink: alsa_output.pci-0000_00_1b.0.analog-stereo
07:48:18.11 - PulseEffects - INFO - default pulseaudio sink audio format: s16le
07:48:18.11 - PulseEffects - INFO - default pulseaudio sink sampling rate: 44100 Hz. We will use the same rate.
07:48:18.11 - PulseEffects - INFO - default pulseaudio source audio format: s16le
07:48:18.12 - PulseEffects - INFO - default pulseaudio source sampling rate: 44100 Hz. We will use the same rate.
07:48:18.12 - PulseEffects - INFO - loading Pulseeffects applications sink...
07:48:18.13 - PulseEffects - INFO - sink owner module index: 27
07:48:18.13 - PulseEffects - INFO - Pulseeffects apps sink was successfully loaded
07:48:18.13 - PulseEffects - INFO - Pulseeffects apps sink index:1
07:48:18.13 - PulseEffects - INFO - Pulseeffects apps sink monitor name: PulseEffects_apps.monitor
07:48:18.13 - PulseEffects - INFO - loading Pulseeffects microphone output sink...
07:48:18.14 - PulseEffects - INFO - sink owner module index: 28
07:48:18.16 - PulseEffects - INFO - Pulseeffects mic sink was successfully loaded
07:48:18.16 - PulseEffects - INFO - Pulseeffects mic sink index:2
07:48:18.16 - PulseEffects - INFO - Pulseeffects mic sink monitor name: PulseEffects_mic.monitor
07:48:18.55 - PulseEffects - INFO - limiter plugin was enabled
07:48:18.55 - PulseEffects - INFO - compressor plugin was enabled
07:48:18.56 - PulseEffects - INFO - reverb plugin was enabled
07:48:18.56 - PulseEffects - INFO - highpass plugin was enabled
07:48:18.56 - PulseEffects - INFO - lowpass plugin was enabled
07:48:18.56 - PulseEffects - INFO - equalizer plugin was enabled
07:48:18.56 - PulseEffects - INFO - spectrum plugin was enabled
07:48:18.59 - PulseEffects - INFO - apps: panorama plugin was enabled
07:48:18.59 - PulseEffects - INFO - apps: output plugin was enabled
07:48:18.66 - PulseEffects - INFO - limiter plugin was enabled
07:48:18.67 - PulseEffects - INFO - compressor plugin was enabled
07:48:18.67 - PulseEffects - INFO - reverb plugin was enabled
07:48:18.67 - PulseEffects - INFO - highpass plugin was enabled
07:48:18.67 - PulseEffects - INFO - lowpass plugin was enabled
07:48:18.68 - PulseEffects - INFO - equalizer plugin was enabled
07:48:18.68 - PulseEffects - INFO - spectrum plugin was enabled
07:48:18.261 - PulseEffects - INFO - apps: equalizer plugin was enabled
07:48:18.469 - PulseEffects - INFO - apps: spectrum plugin was enabled
07:48:18.469 - PulseEffects - INFO - mic: spectrum plugin was enabled
07:49:36.865 - PulseEffects - INFO - pipeline state: playing
```

And the window screenshot https://i.imgur.com/MMSRaAw.png

**Comment by prometheanfire** [comment]
That's without the two lines in default.pa

**Comment by prometheanfire** [comment]
with `load-module module-dbus-protocol` enabled though I get the equalizer, but with a ton of gtk warnings.

```
(pulseeffects:15550): Gtk-WARNING **: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node block, owner GtkLevelBar)

(pulseeffects:15550): Gtk-WARNING **: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node block, owner GtkLevelBar
```

**Comment by prometheanfire** [comment]
and now I understand the interface better, I didn't see how to select the application (my suggestion is to call that out a bit more explicitly somehow).  The enabling of the application is good, but the selecting of it (to set settings on the app) is non-obvious (at least to me).

Other than that everything is working, thanks :D

**Comment by wwmm** [comment]
Log output is fine. And the gtk warnings are no harm and related to a bug that gtk developers are aware of. Nothing to worry about.

**Comment by wwmm** [comment]
I was going to tell you just that XD

**Comment by wwmm** [comment]
The interface is not as intuitive as it should be for new users

**Comment by prometheanfire** [comment]
I'm good with closing this if you are then

**Comment by wwmm** [comment]
I am not an interface designer. So PE window has its flaws... I hope to learn more and improve it over time

**Comment by wwmm** [comment]
ok
