### ISSUE TITLE
Doesn't open

### ISSUE THREAD

**Issue by ptkato** [wwmm/pulseeffects#135]
Are there anything that needs to be done after installing it? I'm on xmonad and installed from AUR, when I type `pulseeffects` some info prompts and python errors appear and nothing else.

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/PulseEffects/application.py", line 74, in do_startup
    self.sie = SinkInputEffects(self.pm)
  File "/usr/lib/python3.6/site-packages/PulseEffects/sink_input_effects.py", line 51, in __init__
    self.exciter = Exciter(self.settings)
  File "/usr/lib/python3.6/site-packages/PulseEffects/exciter.py", line 31, in __init__
    self.build_bin()
  File "/usr/lib/python3.6/site-packages/PulseEffects/exciter.py", line 47, in build_bin
    self.exciter.set_property('bypass', True)
AttributeError: 'NoneType' object has no attribute 'set_property'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/PulseEffects/application.py", line 164, in do_command_line
    self.do_activate()
  File "/usr/lib/python3.6/site-packages/PulseEffects/application.py", line 151, in do_activate
    self.init_ui()
  File "/usr/lib/python3.6/site-packages/PulseEffects/application.py", line 102, in init_ui
    self.sie.init_ui()
AttributeError: 'Application' object has no attribute 'sie'
^CTraceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/PulseEffects/application.py", line 171, in do_shutdown
    self.sie.set_state('null')
AttributeError: 'Application' object has no attribute 'sie'
```

**Comment by wwmm** [comment]
This error is happening because you do not have calf plugins installed. But this is supposed to be an optional plugin. I will fix the code and release a new version that should not crash when optional plugins are missing

**Comment by wwmm** [comment]
I release a new version, `3.1.1`, that does not crashes when these plugins are unavailable. In case you want  to use the `Exciter` and the `Bass Enhancer` make sure you have Calf Studio plugins and the package lilv installed
