### ISSUE TITLE
segfault on Arch Linux

### ISSUE THREAD

**Issue by glaubersm** [wwmm/pulseeffects#267]
I have just installed pulseeeffects on Arch Linux from AUR, it crashes at startup.

```
#0  0x000056124b0c0a3d in PipelineBase::PipelineBase(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int const&) (this=0x56124c81e240, tag=..., sampling_rate=<error reading variable>)
    at /usr/include/sigc++-2.0/sigc++/signal.h:4311
#1  0x000056124b0ace7b in SinkInputEffects::SinkInputEffects(PulseManager*) (this=0x56124c81e240, pulse_manager=0x56124c8f2800)
    at /usr/include/c++/8.1.1/bits/basic_string.h:252
#2  0x000056124b076123 in std::make_unique<SinkInputEffects, PulseManager*>(PulseManager*&&) () at /usr/include/c++/8.1.1/bits/unique_ptr.h:830
#3  0x000056124b076123 in Application::on_startup() (this=0x56124c735f40)
    at ../src/application.cpp:75
#4  0x00007f70cb7b4c50 in Gio::Application_Class::startup_callback(_GApplication*) () at /usr/lib/libgiomm-2.4.so.1
#5  0x00007f70cd55aa4d in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#6  0x00007f70cd56df18 in  () at /usr/lib/libgobject-2.0.so.0
#7  0x00007f70cd5766f6 in g_signal_emit_valist ()
    at /usr/lib/libgobject-2.0.so.0
#8  0x00007f70cd577130 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#9  0x00007f70cc731cf3 in g_application_register () at /usr/lib/libgio-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#10 0x00007f70cc732540 in  () at /usr/lib/libgio-2.0.so.0
#11 0x00007f70cb7b480c in Gio::Application::local_command_line_vfunc(char**&, int&) ()
    at /usr/lib/libgiomm-2.4.so.1
#12 0x00007f70cb7b4a50 in Gio::Application_Class::local_command_line_vfunc_callback(_GApplication*, char***, int*) () at /usr/lib/libgiomm-2.4.so.1
#13 0x00007f70cc7328e2 in g_application_run () at /usr/lib/libgio-2.0.so.0
#14 0x000056124b072f4e in main (argc=1, argv=0x7ffdbe923fe8) at src/pulseeffects.cpp:28
#15 0x00007f70c97c1f4b in __libc_start_main (main=
    0x56124b072ed0 <main>, argc=1, argv=0x7ffdbe923fe8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffdbe923fd8) at ../csu/libc-start.c:308
#16 0x000056124b073a9a in _start () at ../sysdeps/x86_64/start.S:120


```

**Comment by wwmm** [comment]
Strange. I compiled the aur package here a few minutes ago and is running fine. did you make any system upgrade that may require a reboot?

**Comment by glaubersm** [comment]
Yes, updated to pulseaudio 12.1 some hours ago.
Restart my system solved the problem. Sorry.
