### ISSUE TITLE
ImportError: No module named 'numpy'

### ISSUE THREAD

**Issue by coffeverton** [wwmm/pulseeffects#31]
Hi, I just tried to install and got this error.

I'm in Ubuntu 17.04.

The full error message is this:
Traceback (most recent call last):
  File "/usr/local/bin/pulseeffects", line 4, in <module>
    __import__('pkg_resources').run_script('PulseEffects==1.6.7', 'pulseeffects')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/PulseEffects-1.6.7-py3.5.egg/EGG-INFO/scripts/pulseeffects", line 4, in <module>
    from PulseEffects.application import Application
  File "/usr/local/lib/python3.5/dist-packages/PulseEffects-1.6.7-py3.5.egg/PulseEffects/application.py", line 16, in <module>
    from PulseEffects.sink_input_effects import SinkInputEffects
  File "/usr/local/lib/python3.5/dist-packages/PulseEffects-1.6.7-py3.5.egg/PulseEffects/sink_input_effects.py", line 6, in <module>
    import numpy as np
ImportError: No module named 'numpy'

**Comment by wwmm** [comment]
Hi, you need to install the package python-numpy for python 3.

**Comment by coffeverton** [comment]
I tried to do so, but it seems that my default python version is 2.7.

When I ran `sudo pip install numpy`, I got this:

Requirement already satisfied: numpy in /usr/local/lib/python2.7/dist-packages

**Comment by Keepco** [comment]
I guess you could either:
1) Install `python-numpy` and `python-scipy` via apt, which should install both the python 3 and 2 version ( don't quote me on that though, I don't know ubuntu too well )
2) run `sudo pip3 install numpy` ( or if pip3 isn't available you could use easy_install3 )

**Comment by coffeverton** [comment]
Well, it doesn't work. But thanks anyway.
