### ISSUE TITLE
ImportError: libgfortran.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by deikatsuo** [wwmm/pulseeffects#32]
```
Traceback (most recent call last):
  File "/usr/bin/pulseeffects", line 4, in <module>
    from PulseEffects.application import Application
  File "/usr/lib/python3.6/site-packages/PulseEffects/application.py", line 17, in <module>
    from PulseEffects.sink_input_effects import SinkInputEffects
  File "/usr/lib/python3.6/site-packages/PulseEffects/sink_input_effects.py", line 7, in <module>
    from scipy.interpolate import CubicSpline
  File "/usr/lib/python3.6/site-packages/scipy/interpolate/__init__.py", line 176, in <module>
    from .interpolate import *
  File "/usr/lib/python3.6/site-packages/scipy/interpolate/interpolate.py", line 20, in <module>
    import scipy.linalg
  File "/usr/lib/python3.6/site-packages/scipy/linalg/__init__.py", line 175, in <module>
    from .misc import *
  File "/usr/lib/python3.6/site-packages/scipy/linalg/misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "/usr/lib/python3.6/site-packages/scipy/linalg/blas.py", line 155, in <module>
    from scipy.linalg import _fblas
ImportError: libgfortran.so.4: cannot open shared object file: No such file or directory

```

**Comment by wwmm** [comment]
Hi, your system's scipy package was linked to a newer gcc but your installation is using an older one. You probably have libgfortran.so.3 installed. You should contact your distribution package managers. At least in Arch Linux there is a package gcc-libs with the file /usr/lib/libgfortran.so.4

**Comment by deikatsuo** [comment]
Thanks.
![screenshot from 2017-07-01 21-43-15](https://user-images.githubusercontent.com/8337409/27763025-515efaf8-5ea6-11e7-8603-cd14468f296a.png)
