### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'set_property' when calling self.audio_src.set_property('volume', 1.0)

### ISSUE THREAD

**Issue by JackHack96** [wwmm/pulseeffects#35]
I'm on Ubuntu 17.04 and I tried to install the latest version of pulseeffects directly from this Git repo.
I'm sure I installed all the dependecies, and the `gst-inspect-1.0 | grep -i ladspa` command does give me a lot of output, however there's no way to start the app. It always gives me the following errors:
```
16:53:44.491 - PulseEffects - INFO - pulseaudio context started
16:53:44.491 - PulseEffects - INFO - connected to server: unix:/run/user/1000/pulse/native
16:53:44.493 - PulseEffects - INFO - server protocol version: 32
16:53:44.498 - PulseEffects - INFO - pulseaudio version: 10.0
16:53:44.498 - PulseEffects - INFO - default pulseaudio source: alsa_input.pci-0000_00_07.0.analog-stereo
16:53:44.498 - PulseEffects - INFO - default pulseaudio sink: alsa_output.pci-0000_00_07.0.analog-stereo
16:53:44.499 - PulseEffects - INFO - default pulseaudio sink audio format: s16le
16:53:44.499 - PulseEffects - INFO - default pulseaudio sink sampling rate: 44100 Hz. We will use the same rate.
16:53:44.500 - PulseEffects - INFO - default pulseaudio source audio format: s16le
16:53:44.500 - PulseEffects - INFO - default pulseaudio source sampling rate: 48000 Hz. We will use the same rate.
16:53:44.501 - PulseEffects - INFO - loading Pulseeffects applications sink...
16:53:44.501 - PulseEffects - INFO - Pulseeffects apps sink was successfully loaded
16:53:44.504 - PulseEffects - INFO - Pulseeffects apps sink index:1
16:53:44.504 - PulseEffects - INFO - Pulseeffects apps sink monitor name: PulseEffects_apps.monitor
16:53:44.504 - PulseEffects - INFO - loading Pulseeffects microphone output sink...
16:53:44.530 - PulseEffects - INFO - Pulseeffects mic sink was successfully loaded
16:53:44.530 - PulseEffects - INFO - Pulseeffects mic sink index:2
16:53:44.530 - PulseEffects - INFO - Pulseeffects mic sink monitor name: PulseEffects_mic.monitor
Traceback (most recent call last):
  File "/usr/local/bin/pulseeffects", line 4, in <module>
    __import__('pkg_resources').run_script('PulseEffects==2.0.3', 'pulseeffects')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/PulseEffects-2.0.3-py3.5.egg/EGG-INFO/scripts/pulseeffects", line 6, in <module>
    a = Application()
  File "/usr/local/lib/python3.5/dist-packages/PulseEffects-2.0.3-py3.5.egg/PulseEffects/application.py", line 62, in __init__
    self.sie = SinkInputEffects(self.pm.default_sink_rate)
  File "/usr/local/lib/python3.5/dist-packages/PulseEffects-2.0.3-py3.5.egg/PulseEffects/sink_input_effects.py", line 65, in __init__
    self.pipeline = self.build_pipeline()
  File "/usr/local/lib/python3.5/dist-packages/PulseEffects-2.0.3-py3.5.egg/PulseEffects/sink_input_effects.py", line 120, in build_pipeline
    self.audio_src.set_property('volume', 1.0)
AttributeError: 'NoneType' object has no attribute 'set_property'
```
Also, it gives me this error with older version. The only one that worked so far is the packaged version which one can found at Launchpad.net ([https://launchpad.net/~yunnxx/+archive/ubuntu/gnome3/+files/pulseeffects_1.312entornosgnulinuzesty-1ubuntu1_amd64.deb](https://launchpad.net/~yunnxx/+archive/ubuntu/gnome3/+files/pulseeffects_1.312entornosgnulinuzesty-1ubuntu1_amd64.deb)).
I can't figure out what's wrong :(

**Comment by wwmm** [comment]
Hi, for some reason your gstreamer installation does not have the plugin pulsesrc. What is very strange considering that you can run the old version package. At least in Arch Linux this plugin is the the `gst-plugins-good` package. I don't know how this package is called in ubuntu. What is the output of the command `gst-inspect-1.0 pulsesrc`?

**Comment by JackHack96** [comment]
The command wasn't giving me any output. I've solved by reinstalling every gstreamer-related package (if anyone has this problem, run `sudo apt install --reinstall $(dpkg --get-selections | grep gst | cut -f1)`, this will reinstall all the needed packages).

Now the app runs, but it can't change the sound. Now if I run it from the terminal, it continuously gives this message:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/PulseEffects-2.0.3-py3.5.egg/PulseEffects/sink_input_effects.py", line 410, in on_message_element
    magnitudes = msg.get_structure().get_value('magnitude')
TypeError: unknown type GstValueList
```
And the spectrum is black...

**Comment by JackHack96** [comment]
Ok I've seen now that's because of GStreamer 1.10.
That's why the packaged version worked well.
Unfortunately it's not easy to get GStreamer 1.12 on Ubuntu 17.04, so I'll stick with the old version.
Thanks for helping ;)
