### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'set_property'

### ISSUE THREAD

**Issue by Ixoos** [wwmm/pulseeffects#38]
I tried installing pulseeffects directly from the sources, I installed all required libraries but when i run last command error occurs
```
 [ixoos@Igor-Laptop pulseeffects]$ GSETTINGS_SCHEMA_DIR=share/glib-2.0/schemas/ ./pulseeffects
 08:57:08.305 - PulseEffects - INFO - pulseaudio context started
 08:57:08.305 - PulseEffects - INFO - connected to server: unix:/run/user/1000/pulse/native
 08:57:08.305 - PulseEffects - INFO - server protocol version: 32
 08:57:08.306 - PulseEffects - INFO - pulseaudio version: 10.0
 08:57:08.306 - PulseEffects - INFO - default pulseaudio source: bluez_sink.A0_E9_DB_5D_24_83.a2dp_sink.monitor
 08:57:08.306 - PulseEffects - INFO - default pulseaudio sink: bluez_sink.A0_E9_DB_5D_24_83.a2dp_sink
 08:57:08.306 - PulseEffects - INFO - default pulseaudio sink audio format: s16le
 08:57:08.306 - PulseEffects - INFO - default pulseaudio sink sampling rate: 44100 Hz. We will use the same rate.
 08:57:08.307 - PulseEffects - INFO - default pulseaudio source audio format: s16le
 08:57:08.307 - PulseEffects - INFO - default pulseaudio source sampling rate: 44100 Hz. We will use the same rate.
 08:57:08.307 - PulseEffects - INFO - loading Pulseeffects applications sink...
 08:57:08.307 - PulseEffects - INFO - Pulseeffects apps sink was successfully loaded
 08:57:08.307 - PulseEffects - INFO - Pulseeffects apps sink index:2
 08:57:08.307 - PulseEffects - INFO - Pulseeffects apps sink monitor name: PulseEffects_apps.monitor
 08:57:08.307 - PulseEffects - INFO - loading Pulseeffects microphone output sink...
 08:57:08.308 - PulseEffects - INFO - Pulseeffects mic sink was successfully loaded
 08:57:08.308 - PulseEffects - INFO - Pulseeffects mic sink index:3
 08:57:08.308 - PulseEffects - INFO - Pulseeffects mic sink monitor name: PulseEffects_mic.monitor
 Traceback (most recent call last):
   File "./pulseeffects", line 6, in <module>
     a = Application()
   File "/home/ixoos/pulseeffects/PulseEffects/application.py", line 63, in __init__
     self.sie = SinkInputEffects(self.pm.default_sink_rate)
   File "/home/ixoos/pulseeffects/PulseEffects/sink_input_effects.py", line 65, in __init__
     self.pipeline = self.build_pipeline()
   File "/home/ixoos/pulseeffects/PulseEffects/sink_input_effects.py", line 176, in build_pipeline
     self.output_limiter.set_property('input-gain', 0)
 AttributeError: 'NoneType' object has no attribute 'set_property'
```
I'm using fedora 26

**Comment by wwmm** [comment]
Hi, gstreamer is not finding the swh-plugins. What is the output of the command 'gst-inspect-1.0 | grep -i ladspa' ?

**Comment by Ixoos** [comment]
`[ixoos@Igor-Laptop ~]$ gst-inspect-1.0 | grep -i ladspa
ladspa:  ladspa-filter-so-lpf: Simple Low Pass Filter
ladspa:  ladspa-filter-so-hpf: Simple High Pass Filter
ladspa:  ladspa-ladspa-rubberband-so-rubberband-pitchshifter-mono: Rubber Band Mono Pitch Shifter
ladspa:  ladspa-ladspa-rubberband-so-rubberband-pitchshifter-stereo: Rubber Band Stereo Pitch Shifter
ladspa:  ladspa-delay-so-delay-5s: Simple Delay Line
ladspa:  ladspa-amp-so-amp-mono: Mono Amplifier
ladspa:  ladspa-amp-so-amp-stereo: Stereo Amplifier
ladspa:  ladspasrc-noise-so-noise-white: White Noise Source
ladspa:  ladspa-sine-so-sine-faaa: Sine Oscillator (Freq:audio, Amp:audio)
ladspa:  ladspa-sine-so-sine-faac: Sine Oscillator (Freq:audio, Amp:control)
ladspa:  ladspa-sine-so-sine-fcaa: Sine Oscillator (Freq:control, Amp:audio)
ladspa:  ladspasrc-sine-so-sine-fcac: Sine Oscillator (Freq:control, Amp:control)
`

**Comment by wwmm** [comment]
:)
