### ISSUE TITLE
'NoneType' object has no attribute 'set_property'

### ISSUE THREAD

**Issue by Epictek** [wwmm/pulseeffects#49]
```
$ pulseeffects
06:53:29.855 - PulseEffects - INFO - pulseaudio context started
06:53:29.855 - PulseEffects - INFO - connected to server: 127.0.0.1
06:53:29.856 - PulseEffects - INFO - server protocol version: 32
06:53:29.856 - PulseEffects - INFO - pulseaudio version: 10.0-rebootstrapped
06:53:29.856 - PulseEffects - INFO - default pulseaudio source: alsa_input.pci-0000_00_14.2.analog-stereo
06:53:29.856 - PulseEffects - INFO - default pulseaudio sink: alsa_output.pci-0000_09_05.0.analog-stereo
06:53:29.857 - PulseEffects - INFO - default pulseaudio sink audio format: s16le
06:53:29.857 - PulseEffects - INFO - default pulseaudio sink sampling rate: 48000 Hz. We will use the same rate.
06:53:29.858 - PulseEffects - INFO - default pulseaudio source audio format: s16le
06:53:29.858 - PulseEffects - INFO - default pulseaudio source sampling rate: 44100 Hz. We will use the same rate.
06:53:29.858 - PulseEffects - INFO - loading Pulseeffects applications sink...
06:53:29.859 - PulseEffects - INFO - Pulseeffects apps sink was successfully loaded
06:53:29.859 - PulseEffects - INFO - Pulseeffects apps sink index:3
06:53:29.859 - PulseEffects - INFO - Pulseeffects apps sink monitor name: PulseEffects_apps.monitor
06:53:29.859 - PulseEffects - INFO - loading Pulseeffects microphone output sink...
06:53:29.860 - PulseEffects - INFO - Pulseeffects mic sink was successfully loaded
06:53:29.860 - PulseEffects - INFO - Pulseeffects mic sink index:4
06:53:29.860 - PulseEffects - INFO - Pulseeffects mic sink monitor name: PulseEffects_mic.monitor
Traceback (most recent call last):
  File "/usr/bin/pulseeffects", line 6, in <module>
    a = Application()
  File "/usr/lib/python3.5/site-packages/PulseEffects/application.py", line 63, in __init__
    self.sie = SinkInputEffects(self.pm.default_sink_rate)
  File "/usr/lib/python3.5/site-packages/PulseEffects/sink_input_effects.py", line 69, in __init__
    self.pipeline = self.build_pipeline()
  File "/usr/lib/python3.5/site-packages/PulseEffects/sink_input_effects.py", line 179, in build_pipeline
    self.output_limiter.set_property('input-gain', 0)
AttributeError: 'NoneType' object has no attribute 'set_property'
```

**Comment by Epictek** [comment]
Seems like I was missing the `gst1-python3` page for Void Linux.
