### ISSUE TITLE
pulseeffects-3.0.1 and 3.0.2 not load after upgrade

### ISSUE THREAD

**Issue by servimo** [wwmm/pulseeffects#95]
When I tryed to load, after install, pulseeffects 3.0.1 or 3.0.2 gives me this:
"Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/PulseEffects/application.py", line 78, in do_startup
    self.sie = SinkInputEffects(self.pm)
  File "/usr/lib/python3.6/site-packages/PulseEffects/sink_input_effects.py", line 23, in __init__
    EffectsBase.__init__(self, self.pm.default_sink_rate, self.settings)
  File "/usr/lib/python3.6/site-packages/PulseEffects/effects_base.py", line 47, in __init__
    entry_label = Gtk.Label(_('<b>Applications</b>'))
  File "/usr/lib/python3.6/gettext.py", line 606, in gettext
    return dgettext(_current_domain, message)
  File "/usr/lib/python3.6/gettext.py", line 570, in dgettext
    codeset=_localecodesets.get(domain))
  File "/usr/lib/python3.6/gettext.py", line 518, in translation
    t = _translations.setdefault(key, class_(fp))
  File "/usr/lib/python3.6/gettext.py", line 254, in __init__
    self._parse(fp)
  File "/usr/lib/python3.6/gettext.py", line 388, in _parse
    plural = v[1].split('plural=')[1]
IndexError: list index out of range
"
I had to downgrade to pulseeffects-3.0.0

**Comment by wwmm** [comment]
This is a problem with the translation file. Which language are you using? If it is Portuguese this should be fixed in PulseEffects 3.0.4. At least it was fixed here in my machine

**Comment by servimo** [comment]
pulseeffects-3.0.4 solved, Thanks :D
